### ISSUE TITLE
Configuration not launching on Ubuntu 16.04

### ISSUE THREAD

**Issue by madhephaestus** [nation-of-makers/odoo-sandbox#1]
`docker-compose --version`
docker-compose version 1.5.2, build unknown

and then run 

`docker-compose up`

produces 

`ERROR: In file './docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.
`

**Comment by placer14** [comment]
docker-compose requires a higher version to support the version-2 format in this repo. Upgrade docker-compose to 1.8.0. Not sure what the minimum version requirement is, but 1.8 will work.

```
[14:47:16] $ docker-compose --version
docker-compose version 1.8.0, build f3628c7
```
